app:
  build: .
  ports:
    - '3000:3000'
  expose:
    - '3000'
  volumes:
    - .:/app
    - /app/out
    - /app/node_modules
  command: node /app/out/bundle.js

webpack-hmr-node:
  build: .
  volumes_from:
    - app
  command: node_modules/.bin/webpack "/app/node_modules/webpack/hot/signal" --hot --watch --config webpack.dev.node.config.js

#webpack-hmr-client:
#  build: .
#  command: node server/dev/index.js
#  volumes:
#    - .:/app
#    - /app/node_modules
#  volumes_from:
#    - server:ro
#  expose:
#    - '3001'
#  ports:
#    - '3001:3001'
